### ISSUE TITLE
Rename Master to Main

### ISSUE THREAD

**Issue by DavidRieman** [DavidRieman/WheelMUD#114]
GitHub made it easy to migrate our branch name to the industry's new default branch name.
I am looking forward to joining this movement at a low risk moment, soon (probably while no PRs are open).

Some things to remember to check after migration:
* Automatic builds and tests still working.
* File preview links (like User Stories HTML) still working.
* Various other links still working.
* Communicated the change.

**Comment by DrunkenImpGameStudio** [comment]
Can be closed.
