### ISSUE TITLE
Improve single-line AnsiBuilder/OutputBuilder flow

### ISSUE THREAD

**Issue by DavidRieman** [DavidRieman/WheelMUD#115]
Where we today use something like:
```
var ab = new AnsiBuilder();
ab.AppendLine("<%red%>Test<%n%>");
...Send(ab.ToString());
```
We should wrap that pattern up into a method that makes it natural to do one-liners, something like: 
`...Send(AnsiBuilder.SingleLine("<%red%>Test<%n%>"))`

**Comment by DrunkenImpGameStudio** [comment]
This has been added to string update 2

**Comment by DrunkenImpGameStudio** [comment]
Obsolete now. Can be closed.
