### ISSUE TITLE
Move WRM to seperate repository

### ISSUE THREAD

**Issue by ghost** [DavidRieman/WheelMUD#119]
We should consider moving WRM to its own repository since it isn't actually WheelMUD but an example. We could add a example/addon repository where they can download it and others.

**Comment by DavidRieman** [comment]
Opening these discussions on how we can restructure what I'd call "Reference Implementations" better, has been on my TODO list for a while.  Thanks for opening this.  :)

Indeed, the current solution isn't great and inflicts some pain (as WR&M isn't marked as a dependency of ServerHarness so doesn't always get built when you want).

I'm not sure yet if _separate repositories_ is the answer (yet?), or separate solution configurations, or essentially separate ServerHarness apps with mostly shared code...  I think this'll take some discussion and ideation.  I'll make a couple discussion threads for Reference Implementations and link here.

**Comment by DavidRieman** [comment]
Created discussions https://github.com/DavidRieman/WheelMUD/discussions/123 and https://github.com/DavidRieman/WheelMUD/discussions/121 to thread these topics and find a game plan.  :)

**Comment by DavidRieman** [comment]
Closing, as the two issues above fully cover these topics better and there's nothing left to address in this issue.
