### ISSUE TITLE
Show "DB" command in console options

### ISSUE THREAD

**Issue by DavidRieman** [DavidRieman/WheelMUD#163]
The "DEBUGEXPLORE" command is shown when typing "?" for help in the server console, but the easier and more convenient form is "DB" which is not exposed to the user.  We should ensure all commands are listed and improve which forms we're showing.

**Comment by JeremyTHolland** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/1196759/208767242-deb49529-e554-4d8b-95d8-49424e18bcbc.png)

**Comment by DavidRieman** [comment]
Yeah that sounds great.

**Comment by DavidRieman** [comment]
#173
