### ISSUE TITLE
Question about getting back into contributing

### ISSUE THREAD

**Issue by axiomatic-io** [DavidRieman/WheelMUD#19]
Hey Dave,

I wanted to get back into this project and wanted to know which repo I should fork: yours or the WheelMUD one? Yours seems to be further ahead and there's no easy way to contact you so I hope this gets there.

Thanks,
Jeremy

**Comment by DavidRieman** [comment]
Yeah, this is the right place.  The other WM org maintainer hadn't been responsive to my queries or pull request, so I forged on ahead here instead.  I've also been away a while but holiday is coming up and I do tend to get more involved while others are.  :)

Github also just pointed out the "Discussions" feature, which, lacking a solid message board anymore - yeah I'll try enabling that so our discussions wont have to be in the issues board.
