### ISSUE TITLE
Migrate Forums to muds.gamedev.com

### ISSUE THREAD

**Issue by DavidRieman** [DavidRieman/WheelMUD#2]
The old CodePlex forums contents have been saved there.  I have the newer forums contents preserved and ready to migrate to muds.gamedev.com as well; just need to wrap up some minor conversion details and pull the trigger.

**Comment by duaneking** [comment]
The servers up when you need it.  I have root on that box as I own the full stack except the hardware (its rented).

**Comment by DavidRieman** [comment]
Moved issues to WheelMUD/WheelMUD.
