### ISSUE TITLE
Generate a shortcut from bin dir to GameConfiguration.DataStoragePath at runtime

### ISSUE THREAD

**Issue by DavidRieman** [DavidRieman/WheelMUD#35]
It's not always obvious where the data for the MUD instance is held. It would help to auto-generate an obvious shortcut from the running bin dir to the GameConfiguration.DataStoragePath where we store the databases.

**Comment by JeremyTHolland** [comment]
@DavidRieman Do you mean the bin dir of the ServerHarness is where the shortcut should go?

**Comment by DavidRieman** [comment]
I mean the folder where we are building to is easy to find; it's close to the Solution file we opened after all.  Like:
`D:\GIT\WheelMUD\binDebug`
So if we put a shortcut in there (or in the `netcoreapp3.1` subfolder) that links to the program data area, like:
`C:\Users\me\AppData\Roaming\WheelMUD\WheelMUD`
then it'll be a lot easier to discover / get to the program data folder from where we're writing code at.  :)

**Comment by DavidRieman** [comment]
Fixed this with `WindowsShortcutFactory` at 2b49f7cc3890b39a2b5e518b97e9b1c831049c59.
