### ISSUE TITLE
Credits command throws an exception for missing file

### ISSUE THREAD

**Issue by JeremyTHolland** [DavidRieman/WheelMUD#53]
![image](https://user-images.githubusercontent.com/1196759/102036452-d995f300-3d90-11eb-9c1b-84eebf38afb5.png)

I put the referenced file in the path from the exception and the command worked. The error handling needs to be more robust or the file needs to be located correctly as a part of the build perhaps?

**Comment by JeremyTHolland** [comment]
And if I should be logging bugs/stuff/issues differently please let me know as I have no insight into your workflow with this project so I just put stuff out there, hopefully in the right way.

**Comment by DavidRieman** [comment]
Yeah IIRC there is supposed to be some code that checks if these file/folder is present at startup and copies them over if they aren't.  Needs looking into.  Filing here was correct process, thanks!

(also: I notice we failed to have `using` on this StreamReader too, which means we aren't guaranteeing disposal of it promptly when done reading.  We should probably fix that too while in here.)

**Comment by JeremyTHolland** [comment]
Ok. Will do

**Comment by JeremyTHolland** [comment]
I was also going to add my name to the credits file. What is the significance of the handles after the developer names? Github usernames?

**Comment by DavidRieman** [comment]
Cool.
When we had prior self-hosted forums and such, contributors generally also used some custom handle there.  It helped pair the two.  Some may have used a name they use for some MUD they played.  It's optional, but if you do have some other alias you want to be paired in there, feel free to add or omit.

**Comment by DavidRieman** [comment]
Closing as I believe we fixed this.
