### ISSUE TITLE
Talent selection step of character creation - View command broken

### ISSUE THREAD

**Issue by JeremyTHolland** [DavidRieman/WheelMUD#55]
When attempting to use the View command with multi-word talent names, an error is returned.

Since this is a specific case for character creation we might not need some sort of delimiter like quotes and could simple look for a string.Contains type of thing. Unless this command is used elsewhere in the code then a more robust solution would make sense.

Anyone have any thoughts or input on the more general case if needed?

**Comment by DavidRieman** [comment]
Between our PRs, this is mostly fixed
