### ISSUE TITLE
StandardExits are not rendering well

### ISSUE THREAD

**Issue by DavidRieman** [DavidRieman/WheelMUD#67]
When we "look" in a room, the exit Things are rendering like this:
```
Here you notice:
  [StandardExit]
```
This is one of the earliest defects someone is likely to notice upon logging in.

DefaultPerceivedRoomRenderer has some TODO notes we could use to guide this - I believe the Perceive helpers mentioned already exist and likely already work well enough.  Exits are a little weird in that their `Name` is not currently helpful, as we are programmatically assigning "[StandardExit]" from a list of exits.  (Eventually we'll stop loading these from the Relational DB when we get a default zone to be seeding the Document DB instead.  Eventually we'll want to make their texts possible to be customized between the multiple rooms they might be a child of, too, but that'll take some thought and discussion.)

For now though, we should make the DefaultPerceivedRoomRenderer query the perceived exits, and if there are any, provide output like:
```
Here you notice:
  Routes: West, East
```
 with some basic coloring, before listing all the other Things perceived in the room.  I think ExitBehavior's GetExitCommandFrom(thisRoom) is what will get the texts like "West" and "East" (or "Enter" or "Up" or whatever the route is).

**Comment by DavidRieman** [comment]
@octave-syndicate is looking into this one

**Comment by octave-syndicate** [comment]
See potential fix at https://github.com/DavidRieman/WheelMUD/pull/84

**Comment by DavidRieman** [comment]
Closing:  This was fixed sufficiently above.  I also have another step forward coming with my next big commit, and additional adjacent improvements will get tracked separately with TODOs and with tickets later.
