### ISSUE TITLE
Remove ITerminal, rename Terminal?

### ISSUE THREAD

**Issue by DavidRieman** [DavidRieman/WheelMUD#92]
Since Terminal is just a collection of basic properties, it seems extremely unlikely that having an extra `ITerminal` abstraction is making anything easier even for mocking/testing.  (We removed a lot of other unhelpful interfaces some time ago and seems we just missed this one.)  Replace `ITerminal` usages with the concrete class name.

Further, the class name `Terminal` makes it sound like it is _doing something_.  Rename this (perhaps to `TerminalOptions`) while we are at it, to better describe what it holds.

**Comment by DrunkenImpGameStudio** [comment]
This is going to requiring quite a bit of restructuring to prevent a circular dependence on WheelMud.Core :/ 
This might need to go into more of a restructering update.

**Comment by DavidRieman** [comment]
Thanks for the analysis.

**Comment by DrunkenImpGameStudio** [comment]
This can be closed now.
